ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: production-ui.keremavci.dev
      paths: [ "/" ]
  tls: []


resources:
  limits:
    cpu: 0.1
    memory: "256Mi"
  requests:
    cpu: 0.1
    memory: "128Mi"

autoscaling:
  enabled: enable
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

env:
 - name: "APP_ENV"
   value: "production"
 - name: "TODO_API_MYSQL_CONNECTION_STRING"
   value: "root:123456@(127.0.0.1:3306)/todo"